"""Compare synthetic browser exports with offline preprocessing.

Input is a local fixture JSON generated by the browser checker. The report
contains counts/hashes only, never raw text, URLs, HTML or input field values.
"""
import argparse
from hashlib import sha256
import json
from pathlib import Path
from phishing.features import extract, FEATURE_VERSION
from phishing.preprocessing import prepare_snapshot, PREPROCESSING_VERSION


def signature(url, html):
    snapshot = prepare_snapshot(url, html, capture_mode='rendered_dom')
    features = extract(snapshot)
    return {'url': features.url, 'dom': features.dom,
            'text_sha256': sha256((features.text or '').encode()).hexdigest(),
            'text_characters': len(features.text or '')}


def compare(case):
    runtime = signature(case['url'], case['extension_html'])
    rendered = signature(case['url'], case['rendered_html'])
    stored = signature(case['url'], case['stored_html'])
    differing = lambda left, right: [key for key in left if left[key] != right[key]]
    return {'case': case['name'], 'rendered_vs_extension_equal': runtime == rendered,
            'rendered_vs_extension_differences': differing(rendered, runtime),
            'stored_vs_rendered_equal': stored == rendered,
            'stored_vs_rendered_differences': differing(stored, rendered),
            'runtime_signature': runtime,
            'snapshot_characters': len(case['extension_html']),
            'snapshot_utf8_bytes': len(case['extension_html'].encode())}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, required=True)
    args = parser.parse_args()
    cases = json.loads(args.input.read_text())
    print(json.dumps({'research_evidence': False, 'preprocessing_version': PREPROCESSING_VERSION,
                      'feature_version': FEATURE_VERSION, 'cases': [compare(case) for case in cases]}))


if __name__ == '__main__':
    main()
